apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    run: hello-app
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: hello-app
